name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    strategy:
      matrix:
        step: [examples, test]
        optimize: [Debug, ReleaseSmall, ReleaseSafe, ReleaseFast]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      - run: zig build ${{ matrix.step }} -Doptimize=${{ matrix.optimize }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      - run: zig fmt --check .

